services:
  bot:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: shiveron-bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Discord
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}

      # Database
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

      # Node
      NODE_ENV: ${NODE_ENV}

    command: >
      sh -c "npx wait-on tcp:db:5432 && node dist/bot.js"

    networks:
      - shiveron-net

  db:
    image: postgres:16-alpine
    container_name: shiveron-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - shiveron_database:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - shiveron-net

volumes:
  pgdata:

networks:
  shiveron-net:
    driver: bridge
