services:
  shiveron_bot:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: shiveron-bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Discord
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}

      # Database
      DB_HOST: shiveron_db
      DB_PORT: 5432
      DB_NAME: /run/secrets/db_name
      DB_USER: /run/secrets/db_user
      DB_PASS_FILE: /run/secrets/db_pass

      # Node
      NODE_ENV: ${NODE_ENV}
    secrets:
      - discord_token
      - db_pass
    networks:
      - shiveron-net

  shiveron_db:
    image: postgres:16-alpine
    container_name: shiveron-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: /run/secrets/db_name
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    secrets:
      - db_name
      - db_user
      - db_pass
    volumes:
      - shiveron_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shiveron-net

secrets:
  discord_token:
    file: ./secrets/discord_token
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_pass:
    file: ./secrets/db_pass

volumes:
  shiveron_db_data:

networks:
  shiveron-net:
    driver: bridge
